title: DIL Analytics Manual
description: 
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://devinnovationlab.github.io/guides/

# Point to content
collections:
  guides:
    permalink: "guides/"
    output: true
    name: Coding guides
  principles:
    permalink: "principles/"
    output: true
    name: Analytics principles
  templates:
    permalink: "templates/"
    output: true
    name: DIL templates
  resources:
    permalink: "resources/"
    output: true
    name: External resources

# Files that will not be rendered in the website
# exclude:

# DIL color scheme
color_scheme: dil

search:
  # Split pages into sections that can be searched individually
  heading_level: 3
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

 # Footer options
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "View on GitHub."
gh_edit_repository: "https://github.com/DevInnovationLab/guides" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
favicon_ico: "/img/avatar.svg"

# Google analytics
ga_tracking: G-9F9LQ86F00
ga_tracking_anonymize_ip: true

# Callouts
callouts:
  bad:
    title: Bad
    color: red
  good:
    title: Good
    color: green
