# Configurations
title:      DIL Analytics Guide      
longtitle:  Development Innovation Lab Analytics Guide
description: >
  Build Jekyll site with the GitBook style.

version:          0.1
gitbook_version:  3.2.3

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

permalink:        /:categories/:title:output_ext


destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
